### ISSUE TITLE
Invalid date on iOS

### ISSUE THREAD

**Issue by stinobook** [stinobook/poho_kassa#11]
![image](https://github.com/stinobook/poho_kassa/assets/51697064/07d72d89-8413-45e5-98fd-18f588453afa)

**Comment by VandeurenGlenn** [comment]
👀

**Comment by stinobook** [comment]
fixed in https://github.com/stinobook/poho_kassa/commit/b740f7eb1afba742fc38a312748674a4f802c1b3
