### ISSUE TITLE
move login code to firebase

### ISSUE THREAD

**Issue by stinobook** [stinobook/poho_kassa#13]
same as you did with https://github.com/stinobook/poho_kassa/commit/ce8070005db7f1bd4b4d46554dcdc53c1f0d560b

**Comment by VandeurenGlenn** [comment]
Que?

**Comment by stinobook** [comment]
![image](https://github.com/stinobook/poho_kassa/assets/51697064/5f217f64-9f7d-452d-a934-8531144f3354)

thought you wanted to move it to firebase.ts as well :)

**Comment by VandeurenGlenn** [comment]
Ok now I can follow, what line is that?

**Comment by stinobook** [comment]
Top of login.ts ;)
