### ISSUE TITLE
Attendance broken

### ISSUE THREAD

**Issue by stinobook** [stinobook/poho_kassa#15]
Attendance doesn't load correctly after refresh

(onchange bugged?)

also if doing promo sale (so key: false in this.promo) you can remove attendance and it will also remove the promo (while it shouldnt when promo has been set to false ) 

```
   for (const [key, value] of Object.entries(this.promo)) {
      if (value && !attendanceKeys.includes(key)) delete this.promo[key]
    }
```

looks right to me though..

think its with the new propertylisteners..

**Comment by VandeurenGlenn** [comment]
@stinobook You broken.
