### ISSUE TITLE
calendar still broken

### ISSUE THREAD

**Issue by stinobook** [stinobook/poho_kassa#16]
![image](https://github.com/stinobook/poho_kassa/assets/51697064/e373f373-d5ae-4a0f-80ef-8d9e14957bb5)

![image](https://github.com/stinobook/poho_kassa/assets/51697064/32dc1739-7c6e-4d99-b247-c0fc324bcbd8)

**Comment by stinobook** [comment]
seems to be happening when removing the last 'active' from a month

**Comment by VandeurenGlenn** [comment]
Fixed!
