### ISSUE TITLE
Sizeable sales-input-buttons

### ISSUE THREAD

**Issue by VandeurenGlenn** [stinobook/poho_kassa#19]
Sales buttons (for me) are way to big, suggest making them resizeable using a slider.

**Comment by stinobook** [comment]
😂 I have 75% scale as default zoom. They still complain some things are too small 😅

**Comment by VandeurenGlenn** [comment]
> 😂 I have 75% scale as default zoom. They still complain some things are too small 😅

ah, maybe we should set the max sizes a bit higher then?

**Comment by VandeurenGlenn** [comment]
now the max font-size is set to 1.3em and height 86px
