### ISSUE TITLE
Upload picture replaces src with object

### ISSUE THREAD

**Issue by stinobook** [stinobook/poho_kassa#25]
![image](https://github.com/stinobook/poho_kassa/assets/51697064/ab511559-ec8b-412a-8503-1a20c21dd972)

page: add-member

after uploading picture, picture doesn't work (only on add-member page):
![image](https://github.com/stinobook/poho_kassa/assets/51697064/3fb4e980-615e-44ff-8528-37697e04a945)

error code: 
![image](https://github.com/stinobook/poho_kassa/assets/51697064/a76491c8-03a4-44bc-a500-53efef92ccb5)

this works to display the picture correctly: 
![image](https://github.com/stinobook/poho_kassa/assets/51697064/2900074c-638f-47e0-90ee-8d4e4b3066b7)

but then upload is broken.

**Comment by VandeurenGlenn** [comment]
![image](https://github.com/stinobook/poho_kassa/assets/8685280/c642c6a4-93f2-4d6d-a548-5d5eccc32a97)
Could check there if its an object or not.

**Comment by stinobook** [comment]
Aha! didnt look there :) fixed with https://github.com/stinobook/poho_kassa/commit/04dd9dce03acd1a496627ad8a53d087b57213a9c
