### ISSUE TITLE
Add member picture selector doens't work on mobile

### ISSUE THREAD

**Issue by stinobook** [stinobook/poho_kassa#4]
![image](https://github.com/stinobook/poho_kassa/assets/51697064/33f68fb7-b9c2-4cdd-ab43-ff2665656876)
this broken

**Comment by VandeurenGlenn** [comment]
> ![image](https://private-user-images.githubusercontent.com/51697064/320847535-33f68fb7-b9c2-4cdd-ab43-ff2665656876.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NjcyOTYsIm5iZiI6MTcxMjc2Njk5NiwicGF0aCI6Ii81MTY5NzA2NC8zMjA4NDc1MzUtMzNmNjhmYjctYjljMi00Y2RkLWFiNDMtZmYyNjY1NjU2ODc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE2MzYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzNDI3ZjA1NmMwYjBlNTMyYWU3N2U0NGRiMTgzYTZkY2RlOWRhMzgzNzI3Y2E3Yzg0MDJlZTExZTc0YmUzMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rhiVK6ik6LonEsvEXySKhth5H1VVhpBH9Zpmswo-1uc) this broken

it was never completed :p

**Comment by VandeurenGlenn** [comment]
fixed in https://github.com/stinobook/poho_kassa/commit/1751356b557d4d00e50c6e82402727c0a3e90245
