### ISSUE TITLE
add account passkeys

### ISSUE THREAD

**Issue by stinobook** [stinobook/poho_kassa#5]
need accounts and ability to restrict accounts to certain menu pages
(so they also dont see the whole menu)

**Comment by VandeurenGlenn** [comment]
@stinobook passkeys are device/account related, this means when used on an Apple or Android device people need to login with their account for that platform.

Passkeys are really awesome but they more personal, iow every poho app user would need to have their own google/apple account, so don't think this is something ideal for a company, service etc

**Comment by VandeurenGlenn** [comment]
@stinobook passkeys are device/account related, this means when used on an Apple or Android device people need to login with their account for that platform.

Passkeys are really awesome but they more personal, iow every poho app user would need to have their own google/apple account, so don't think this is something ideal for a company, service etc
