### ISSUE TITLE
onchange not triggering with database change

### ISSUE THREAD

**Issue by stinobook** [stinobook/poho_kassa#6]
src/views/planning.ts

![image](https://github.com/stinobook/poho_kassa/assets/51697064/b4a4bae5-76bb-431a-850d-fc13372dadcf)

only works on load, but does not get triggered when changing value afterwards

**Comment by VandeurenGlenn** [comment]
Fixed, see https://github.com/stinobook/poho_kassa/commit/5724029678fdf58ff25fbfe0687ea2dd2b196e01#diff-da8faf4ea8929bb887fe5314bbb06842ad6715d4ce1d16c12bea5695f70851fe
