### ISSUE TITLE
Need user accounts

### ISSUE THREAD

**Issue by VandeurenGlenn** [stinobook/poho_kassa#8]
see #5 

todo
====
- [x] need ui to create an account (add create/manage user-view) (@stinobook )
- [x] only show the drawer-item in navbar when an admin is logged in (admin views should only be viewable for admins...) (@stinobook)
- [x] update database rules so that members can view what they need to but nothing more then that... (@stinobook)
- [x] do nothing (@VandeurenGlenn )

**Comment by stinobook** [comment]
done with https://github.com/stinobook/poho_kassa/commit/f094db3f068552923656145fc351e20cfa3804c4
