### ISSUE TITLE
Closing tab makes open tabs invisible until refresh

### ISSUE THREAD

**Issue by stinobook** [stinobook/poho_kassa#9]
When closing a tab, app says no open tabs until page refresh

**Comment by stinobook** [comment]
not happening for me on PC. was happening on ipad..

**Comment by stinobook** [comment]
fixed with https://github.com/stinobook/poho_kassa/commit/ec6207b349bd3905c6d4e21d905708f7eb605c54

@VandeurenGlenn i think all the firebase.onChildRemoved event listeners need that fix. 
![image](https://github.com/stinobook/poho_kassa/assets/51697064/8d0655eb-9356-411d-9310-e69bc7b6fd56)

**Comment by VandeurenGlenn** [comment]
OMG, yes! splice needs 1!
